title: Faiaz Zahin
logo: https://github.com/fzn011/faiazzahin.github.io/blob/main/assets/Faiaz%20Logo.png 
description: Fresh Computer Science Graduate
show_downloads: true
theme: jekyll-theme-minima
