title: Faiaz Zahin
logo: /assets/Faiaz%20Logo.png
description: Fresh Computer Science Graduate
show_downloads: true
theme: jekyll-theme-minimal

# Add this line
plugins:
  - jekyll-seo-tag

# Link custom CSS
markdown: kramdown
sass:
  style: compressed
include:
  - assets/css
